root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main main.go"
exclude_dir = ["tmp"]
include_dir = ["cmd", "views", "static", "models", "routes"]
include_ext = ["go", "html"]

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true